# Generated by Django 2.2.14 on 2020-07-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_data_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_model',
            name='bvnbmv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
